apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeinfo-prod

resources:
- ../../base

patches:
- path: version.yaml
- path: ingress.yaml

openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/main/schema/argo_all_k8s_kustomize_schema.json

nameSuffix: "-prod"

