---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeinfo-canary
spec:
  template:
    spec:
      containers:
      - name: kubeinfo-container
        image: ghcr.io/heymikeey/kube-info/kube-info:v2.2.0
