apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeinfo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeinfo
  template:
    metadata:
      labels:
        app: kubeinfo
    spec:
      containers:
        - name: kubeinfo-container
          image: ghcr.io/heymikeey/kube-info/kube-info:latest
          ports:
            - containerPort: 5000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_NAME
              value: "CaaS"