---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeinfo-deployment
spec:
  template:
    metadata:
      labels:
        app: kubeinfo
    spec:
      containers:
      - name: kubeinfo-container
        image: ghcr.io/heymikeey/kube-info/kube-info:v2.1.0
