---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeinfo-deployment
spec:
  template:
    spec:
      containers:
      - name: kubeinfo-container
        image: ghcr.io/heymikeey/kube-info/kube-info:1.2.0