name: Build and Push Docker Image to GHCR

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

permissions:
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build --build-arg VERSION=${{ github.ref_name }} -t ghcr.io/${{ github.repository }}/kube-info:${{ github.ref_name }} .
          docker build --build-arg VERSION=${{ github.ref_name }} -t ghcr.io/${{ github.repository }}/kube-info:latest .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/kube-info:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/kube-info:latest
